### ISSUE TITLE
PA Review: Notes

### ISSUE THREAD

**Issue by jigajigajoo** [joshstroud/Clevernote#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by eshoule** [comment]
- [x] Logged in users can create and view notes.
- [x] Full CRUD interface: create, read, update, and delete notes.
 * When I click new note nothing happens...I get a 422 error for trying to POST.
- [x] Adequate styling
* The page width always seems to exceed the width of the viewers window - have it fit to the window so the user doesn't have to scroll over to see the rest of their note when typing
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

Josh, it's looking good, but there are a couple of issues. I keep getting POST and PATCH errors when trying to create and update notes.

**Comment by jigajigajoo** [comment]
I am on it. Looks like one of the newer builds I posted to heroku after I submitted crashed my server and the styling...

**Comment by jigajigajoo** [comment]
Ok, I added more seeds and fixed the issues with the server and the styling.

**Comment by eshoule** [comment]
- [x] When I log in as a new user and click new note there is a 400-level error.
- [x] When I delete a note, it is deleted from the index, but the editor still has the deleted note's text.
