### ISSUE TITLE
PA Review: Rich Text Editing

### ISSUE THREAD

**Issue by jigajigajoo** [joshstroud/Clevernote#4]
- [x] Integrate Quill React component
- [x] Add event handling methods
- [x] Style Editor

**Comment by eshoule** [comment]
- [x] Logged in users can edit notes in a rich text editor (using https://quilljs.com/).
- [x] Adequate styling
 * Seems like when you type in a title in the editor and press enter, it is reflected in the notes index
- [x] Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds to demonstrate the feature
* More seeds!

**Comment by jigajigajoo** [comment]
OK, I made the edits. I implement autosave, so it should update after about a second.

I added a lot more seeds! The only issue is that the seeds are filled with images, which stalls the app when you load a new note. I am not sure why it is blocking the app when they are ajax calls, I will check in first thing tomorrow so we can diagnose.
