### ISSUE TITLE
PA Review: Notebooks

### ISSUE THREAD

**Issue by jigajigajoo** [joshstroud/Clevernote#5]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

MVP Feature List
- [x] Logged in users can save notes to notebooks.
- [x] Logged in users can browse and view notebooks.
- [x] Full CRUD interface: create, read, update, and delete notebooks.

**Comment by eshoule** [comment]
Awesome!

- [x] When I sign in with a demo user, sign out, and then sign in with a different user and look at notebooks, the demo user's notebooks show up in the new user's notebooks, but then when I refresh, they all go away.

**Comment by jigajigajoo** [comment]
I fixed the bug! There was an error when updating the notebooks list
